[package]
name = "ezcurl"
version = "0.1.0"
edition = "2024"
description = "ezcurl is postman in the terminal."
repository = "https://github.com/HugoNayl/ezcurl"
license = "Apache-2.0"

[lib]
name = "ezcurl"
path = "src/lib/lib.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.92"
crossterm = "0.29.0"
derive_more = { version = "2.1.1", features = ["full"] }
futures = "0.3.34"
http = "1.5"
ratatui = "0.30.2"
reqwest = { version = "0.13.4", features = ["cookies", "rustls"] }
reqwest_cookie_store = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.3", features = ["full"] }
unicode-width = "0.2.2"

[lints]
clippy = { all = "deny" }
rust = { unsafe_code = "forbid" }

[profile.release]
opt-level = 3
strip = "symbols"
lto = "fat"
codegen-units = 1
